# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4jEHxuC91zSOlEJ1qXOT6ZcquTbaBno
"""

#!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# ---------------------------
# Load model
# ---------------------------
pipeline = joblib.load("pipeline/final_pipeline.pkl")

# ---------------------------
# Streamlit page setup
# ---------------------------
st.set_page_config(page_title="❤️ Heart Disease Predictor", layout="wide")

st.title("❤️ Heart Disease Prediction App")
st.write("This app predicts the likelihood of heart disease based on patient data and provides data visualizations.")

# ---------------------------
# Sidebar input form
# ---------------------------
st.sidebar.header("Enter Patient Data")

def user_input_features():
    age = st.sidebar.slider("Age", 20, 100, 50)
    cp = st.sidebar.selectbox("Chest Pain Type (0-3)", [0,1,2,3])
    trestbps = st.sidebar.slider("Resting Blood Pressure", 80, 200, 120)
    chol = st.sidebar.slider("Serum Cholestoral (mg/dl)", 100, 400, 200)
    thalach = st.sidebar.slider("Max Heart Rate Achieved", 70, 210, 150)
    oldpeak = st.sidebar.slider("ST Depression (oldpeak)", 0.0, 6.0, 1.0)
    ca = st.sidebar.selectbox("Major Vessels Colored by Fluoroscopy (0-4)", [0,1,2,3,4])
    thal = st.sidebar.selectbox("Thal (0-3)", [0,1,2,3])

    data = {
        "age": age,
        "cp": cp,
        "trestbps": trestbps,
        "chol": chol,
        "thalach": thalach,
        "oldpeak": oldpeak,
        "ca": ca,
        "thal": thal
    }
    return pd.DataFrame(data, index=[0])

input_df = user_input_features()

# ---------------------------
# Prediction
# ---------------------------
if st.button("🔍 Predict"):
    prediction = pipeline.predict(input_df)[0]
    st.subheader("Prediction Result:")
    if prediction == 1:
        st.error("💔 High Risk of Heart Disease")
    else:
        st.success("✅ Low Risk of Heart Disease")

# ---------------------------
# Data Visualizations
# ---------------------------
st.markdown("---")
st.header("📊 Heart Disease Data Insights")

try:
    df = pd.read_csv("data/clean_heart.csv")

    # 1. Target distribution
    st.subheader("Target Distribution")
    fig, ax = plt.subplots()
    sns.countplot(x="target", data=df, palette="coolwarm", ax=ax)
    st.pyplot(fig)

    # 2. Age distribution by disease status
    st.subheader("Age Distribution by Heart Disease Status")
    fig, ax = plt.subplots()
    sns.histplot(df, x="age", hue="target", kde=True, palette="coolwarm", ax=ax)
    st.pyplot(fig)

    # 3. Cholesterol vs Age scatter
    st.subheader("Cholesterol vs Age")
    fig = px.scatter(df, x="age", y="chol", color="target",
                     title="Cholesterol vs Age by Heart Disease Status",
                     labels={"chol": "Cholesterol", "age": "Age"})
    st.plotly_chart(fig)

    # 4. Correlation heatmap
    st.subheader("Correlation Heatmap")
    fig, ax = plt.subplots(figsize=(10,6))
    sns.heatmap(df.corr(), cmap="coolwarm", annot=False, ax=ax)
    st.pyplot(fig)

    # 5. Resting blood pressure boxplot
    st.subheader("Resting Blood Pressure by Heart Disease Status")
    fig, ax = plt.subplots()
    sns.boxplot(x="target", y="trestbps", data=df, palette="coolwarm", ax=ax)
    st.pyplot(fig)

except Exception as e:
    st.warning("Dataset not found for visualization. Please ensure 'data/heart_disease.csv' exists.")
    st.text(f"Error: {e}")
